package judexis.core.behavior.modules.base;

public enum BufferChannel {
    HORIZONTAL,
    VERTICAL,
    ROTATION,
    YAW,
    PITCH,
    ATTACK_INTERVAL,
    PLACE_INTERVAL,
    BREAK_INTERVAL,
    TRANSACTION_INTERVAL,
    PACKET_INTERVAL,
    REACH_DISTANCE,
    VELOCITY_REDUCTION,
    STRAFE_ERROR,
    DISPLACEMENT_BURST,
    TARGET_SWITCH_INTERVAL,
    FOV_MISMATCH
}
