package io.judexis.core.decision;

/**
 * Immutable decision projection generated by a decision engine.
 */
public final class Decision {
    private final DecisionOutcome outcome;
    private final double score;
    private final String reason;

    public Decision(DecisionOutcome outcome, double score, String reason) {
        if (outcome == null) {
            throw new IllegalArgumentException("outcome is required");
        }
        this.outcome = outcome;
        this.score = score;
        this.reason = reason == null ? "" : reason;
    }

    public DecisionOutcome getOutcome() {
        return outcome;
    }

    public double getScore() {
        return score;
    }

    public String getReason() {
        return reason;
    }

    public static Decision none() {
        return new Decision(DecisionOutcome.NONE, 0.0D, "");
    }
}
