name: Judexis
main: io.judexis.adapter.v1_8.JudexisPlugin
version: 0.1.0-SNAPSHOT
author: Judexis
description: Judexis adapter for PaperSpigot 1.8.8
commands:
  judexis:
    description: Judexis runtime debug and check control
    usage: /judexis <debug|toggle>
    permission: judexis.command
permissions:
  judexis.command:
    default: op
